### ISSUE TITLE
Remove mandatory destination directory

### ISSUE THREAD

**Issue by felipemmelo** [AbsaOSS/hyperdrive#105]
Not every writer will have a destination directory, e.g. Kafka. 

However, [this](https://github.com/AbsaOSS/hyperdrive/blob/develop/driver/src/main/scala/za/co/absa/hyperdrive/driver/SparkIngestor.scala#L142) line is making it mandatory.

**Comment by kevinwallimann** [comment]
This has been fixed in #88 . I haven't merged it to develop yet, but only to branch release/3.0.0, because it's a breaking change. I suggest you check out branch release/3.0.0 for now.
