### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by jozefbakus** [AbsaOSS/hyperdrive#231]
In spark structured streaming we experience Out of memory error after several micro-batches.
Possibly memory leak.

ERROR Utils: uncaught error in thread spark-listener-group-eventLog, stopping SparkContext
java.lang.OutOfMemoryError: Java heap space

ERROR MicroBatchExecution: Query [id = x, runId = y] terminated with error
java.lang.OutOfMemoryError: GC overhead limit exceeded

Set up:
Hadoop: 2.7.3.2.6.4.0-91
Spark: spark-2.4.4

**Comment by kevinwallimann** [comment]
Out of memory happened because of too large default values for the (in-memory) Spark UI

Resolved by setting
```
spark.sql.ui.retainedExecutions=25
spark.streaming.ui.retainedBatches=50
spark.ui.retainedStages=50
spark.worker.ui.retainedDrivers=50
spark.ui.retainedJobs=50
spark.worker.ui.retainedExecutors=50
spark.ui.retainedTasks=500
```
