### ISSUE TITLE
Driver - if no properties file found, use the template

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/hyperdrive#33]
I suggest that if the compiler does not find any properties file in the resources of the driver module, to copy over the template which, if I understand it correctly should be usable for the basic use case of the hyperdrive and maybe to demonstrate how it works.

This is done with modules within Enceladus as well from a pom file. The plugin used is `maven-antrun-plugin` please check [here](https://github.com/AbsaOSS/enceladus/blob/develop/menas/pom.xml#L292)

**Comment by kevinwallimann** [comment]
Hmm I'm not sure if I get it right. The path to the properties file always has to be passed as an argument to the [PropertiesIngestionDriver](https://github.com/AbsaOSS/hyperdrive/blob/develop/driver/src/main/scala/za/co/absa/hyperdrive/driver/drivers/PropertiesIngestionDriver.scala#L35), it's not loaded from classpath. So you have to execute it with
`spark-submit driver-1.0.0-SNAPSHOT.jar Ingestion.properties.template` Thus, I don't see the benefit of copying `src/main/resources/Ingestion.properties.template` to `src/main/resources/Ingestion.properties`

If the user doesn't have a properties file, do you imagine this should be possible?
`spark-submit driver-1.0.0-SNAPSHOT.jar`?

**Comment by Zejnilovic** [comment]
Ok, I see what is happening more clearly now. I think it is a good idea to force users to make a conscious decision.
